version: '3.7'

services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud-server
    restart: always
    ports:
      - 8080:8080
    environment:
      - OWNCLOUD_DOMAIN=192.168.19.129
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    depends_on:
      - db
    volumes:
      - owncloud_files:/mnt/data

  db:
    image: mysql:8.0
    container_name: owncloud-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
    volumes:
      - db_data:/var/lib/mysql

volumes:
  owncloud_files:
  db_data:
