---
- name: Rsync Backup Cron Job Setup
  hosts: mainserver
  become: yes
  tasks:
    - name: backup.sh dosyasını kopyala
      copy:
        src: ../files/backup.sh
        dest: /usr/local/bin/backup.sh
        mode: '0755'

    - name: Her gün saat 2:00'de backup.sh scriptini çalıştıracak cron job ekle
      cron:
        name: "Daily Rsync Backup"
        minute: "0"
        hour: "2"
        job: "/usr/local/bin/backup.sh"
