---
- name: Syslog Server Kurulumu
  hosts: backupserver
  become: yes

  tasks:
    - name: Rsyslog paketinin yüklü olduğunu doğrula
      apt:
        name: rsyslog
        state: present
        update_cache: yes

    - name: Rsyslog konfigürasyon dosyasını düzenle (514 UDP dinleme)
      copy:
        dest: /etc/rsyslog.d/remote.conf
        content: |
          # Remote syslog messages
          module(load="imudp")
          input(type="imudp" port="514")

          template(name="RemoteLogs" type="string" string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log")
          action(type="omfile" dynaFile="RemoteLogs")

    - name: Rsyslog servisini yeniden başlat
      systemd:
        name: rsyslog
        state: restarted
        enabled: yes

    - name: Loglar için klasör oluştur
      file:
        path: /var/log/remote
        state: directory
        mode: '0755'
