---
- name: Backup Server'ı LDAP client yapmak
  hosts: backupserver
  become: true

  vars:
    ldap_server_uri: "ldap://192.168.19.129"
    ldap_base_dn: "dc=reklamajansi,dc=com"

  tasks:

    - name: Gerekli paketleri yükle
      apt:
        name:
          - libnss-ldap
          - libpam-ldap
          - ldap-utils
          - nscd
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: /etc/ldap dizinini oluştur
      file:
        path: /etc/ldap
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: /etc/ldap/ldap.conf dosyasını oluştur ve ayarla
      copy:
        dest: /etc/ldap/ldap.conf
        content: |
          BASE {{ ldap_base_dn }}
          URI {{ ldap_server_uri }}
        owner: root
        group: root
        mode: '0644'

    - name: /etc/nsswitch.conf dosyasını güncelle (passwd için ldap ekle)
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^passwd:'
        line: 'passwd:         files systemd ldap'

    - name: /etc/nsswitch.conf group satırını güncelle
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^group:'
        line: 'group:          files systemd ldap'

    - name: /etc/nsswitch.conf shadow satırını güncelle
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^shadow:'
        line: 'shadow:         files ldap'

    - name: PAM ayarını yap - Home directory otomatik oluşturulsun
      lineinfile:
        path: /etc/pam.d/common-session
        insertafter: '^session required pam_unix.so'
        line: 'session required pam_mkhomedir.so skel=/etc/skel umask=0022'
        state: present

    - name: nscd servisini restart et
      systemd:
        name: nscd
        state: restarted

